import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    // A simple function (t) to get localized strings
    t: (key: string) => string;
}

// Very basic dictionary for core Navigation and structural text. We can expand this.
const translations: Record<Language, Record<string, string>> = {
    en: {
        'nav.explore': 'EXPLORE',
        'nav.profile': 'PROFILE',
        'nav.upload': 'UPLOAD_',
        'nav.logout': 'LOGOUT_',
        'nav.login': 'Login',
        'nav.register': 'Register',
        'upload.title': 'Upload Note',
        'profile.settings': 'Settings',
        'home.hero.title_1': 'Capture your thoughts,',
        'home.hero.title_2': 'refine',
        'home.hero.title_3': ' into knowledge.',
        'home.hero.desc': 'The minimalist workspace for students to jot down quick notes, refine them into study materials, and share via secure 4-digit PINs.',
        'home.hero.launch': 'LAUNCH DASHBOARD_',
        'home.hero.start': 'GET STARTED_',
        'home.hero.explore': 'EXPLORE NOTES_',
        'home.why.rapid': 'Rapid Capture',
        'home.why.rapid_desc': '"Jot" down raw thoughts instantly before they fade. No distractions, just your ideas.',
        'home.why.clean': 'Clean Refinement',
        'home.why.clean_desc': 'Turn messy scribbles into structured, searchable study materials with Markdown support.',
        'home.why.simple': 'Simple Sharing',
        'home.why.simple_desc': 'Share your work with a 4-digit PIN. Keep things private or open to the world in a click.',
        'home.pin.title': 'Secure by PIN or PAPS',
        'home.pin.desc_1': 'Share your entire public profile or specific notes using your unique 4-digit Secret Code or PAPS.',
        'home.pin.desc_2': 'Others can access your content at ',
        'home.pin.desc_3': ' only if they know your PIN or pay the PAPS price you set.',
        'home.cta.title': 'Ready to study smarter?',
        'home.cta.button': 'INITIALIZE JOINT_',
        'dash.total_notes': 'TOTAL NOTES',
        'dash.folders': 'FOLDERS',
        'dash.total_praise': 'TOTAL PRAISE',
        'dash.title': 'My Place',
        'dash.subtitle': 'Your central hub for dropping quick notes and organizing into folders.',
        'dash.new_folder': 'NEW FOLDER',
        'dash.cancel': 'CANCEL',
        'dash.quick_add': 'QUICK ADD_',
        'dash.create_folder': 'Create New Folder',
        'dash.folder_name': 'FOLDER NAME',
        'dash.desc_optional': 'DESCRIPTION (Optional)',
        'dash.create': 'CREATE_',
        'dash.inbox': 'Single Notes',
        'dash.not_in_folder': 'not in any folder',
        'dash.move_to': 'Move to folder:',
        'dash.no_folders': 'No folders yet. Create one first.',
        'dash.empty_title': 'Your library is empty',
        'dash.empty_desc': 'Add a quick note, or create a folder to organize your jots.',
        'dash.quick_add_note': 'QUICK ADD NOTE_',
        'dash.create_a_folder': 'CREATE A FOLDER',
        'dash.no_folders_yet': 'No folders yet.',
        'dash.create_one': 'Create one',
        'dash.start_org': 'to start organizing your notes.',
        'dash.save': 'SAVE',
        'dash.notes_count': 'NOTES',
        'upload.return': 'RETURN TO DASHBOARD',
        'upload.page_title': 'Upload Note',
        'upload.select_course': 'SELECT COURSE',
        'upload.no_folder': '-- ADD TO LIBRARY (no folder) --',
        'upload.note_title': 'NOTE TITLE',
        'upload.title_placeholder': 'e.g. Chapter 4...',
        'upload.content': 'CONTENT (Markdown supported)',
        'upload.content_placeholder': 'Write your notes here...',
        'upload.attach_images': 'ATTACH IMAGES',
        'upload.drag_drop': 'DRAG & DROP IMAGES HERE OR CLICK TO BROWSE',
        'upload.uploading': 'UPLOADING...',
        'upload.submit': 'COMMIT. UPLOAD_',
        'set.title': 'Settings',
        'set.profile': 'Profile',
        'set.privacy': 'Privacy',
        'set.wallet': 'Wallet',
        'set.earnings': 'Earnings',
        'set.account': 'Account',
        'set.public_profile': 'Public Profile',
        'set.display_name': 'Display Name',
        'set.name_placeholder': 'Your full name or alias',
        'set.bio': 'Bio',
        'set.bio_placeholder': 'A short description about you...',
        'set.university': 'University',
        'set.uni_placeholder': 'e.g. MIT',
        'set.department': 'Department',
        'set.dept_placeholder': 'e.g. Computer Science',
        'set.save_profile': 'SAVE PROFILE_',
        'set.share_pin': 'Share PIN (4-digit Code)',
        'set.pin_desc1': 'Your PIN is what others enter to access your public profile at',
        'set.current': 'Current:',
        'set.new_pin': 'New PIN',
        'set.set_pin': 'SET PIN_',
        'set.privacy_visibility': 'Privacy & Visibility',
        'set.default_visibility': 'Default Note Visibility',
        'set.private': '🔒 Private',
        'set.public': '🌐 Public',
        'set.private_desc': 'New notes will only be visible to you and users with your PIN.',
        'set.public_desc': 'New notes will be publicly visible and discoverable.',
        'set.show_explore': 'Show on Explore',
        'set.explore_desc': 'Allow your profile to appear in the Explore / Featured section.',
        'set.save_privacy': 'SAVE PRIVACY_',
        'set.paps_balance': 'PAPS Balance',
        'set.available': 'Available',
        'set.tx_history': 'Transaction History',
        'set.no_tx': 'NO TRANSACTIONS YET.',
        'set.this_week': "This Week's Earnings",
        'set.earned': 'Earned',
        'set.spent': 'Spent',
        'set.net': 'Net',
        'set.week_of': 'Week of',
        'set.no_activity': 'No activity this week yet.',
        'set.change_email': 'Change Email',
        'set.new_email': 'New Email',
        'set.current_pwd': 'Current Password',
        'set.update_email': 'UPDATE EMAIL_',
        'set.change_pwd': 'Change Password',
        'set.new_pwd': 'New Password',
        'set.confirm_pwd': 'Confirm New Password',
        'set.update_pwd': 'UPDATE PASSWORD_',
        'set.session': 'Session',
        'set.logout': 'LOGOUT_',
        'set.saving': 'SAVING...',
        'exp.title': 'Explore',
        'exp.subtitle': 'Discover notes and folders from other students. Search by username or browse featured profiles.',
        'exp.search_label': 'SEARCH PROFILES',
        'exp.search_placeholder': 'Username or display name...',
        'exp.searching': 'SEARCHING...',
        'exp.search': 'SEARCH_',
        'exp.found': 'Found',
        'exp.results_for': 'result(s) for',
        'exp.clear': 'Clear Search',
        'exp.search_results': 'Search Results',
        'exp.featured': 'Featured Profiles',
        'exp.searching_void': 'Searching the void...',
        'exp.no_profiles': 'No profiles found matching',
        'exp.try_these': 'Try these instead:',
        'exp.tip1': '• Search by full username or display name',
        'exp.tip2': '• Check for typos',
        'exp.tip3': '• Try searching for "demo" (if available)',
        'exp.no_public': 'No public profiles available yet.',
        'exp.course': 'Folder',
        'exp.try_demo': 'TRY DEMO_',
        'exp.view': 'VIEW_',
        'prof.private_title': 'Private Profile Settings',
        'prof.private_desc': 'Settings and profile management go here.',
        'prof.sys_error': 'System Error',
        'prof.not_found': 'User not found.',
        'prof.encrypted': 'ENCRYPTED_PROFILE',
        'prof.target': 'Target:',
        'prof.enter_pin': 'ENTER 4-DIGIT PIN',
        'prof.decrypting': 'DECRYPTING...',
        'prof.decrypt': 'DECRYPT_ACCESS',
        'prof.sec_protocol': 'Unauthorized access is logged. JOTROW Security Protocol v1.4',
        'prof.read_only': 'PUBLIC READ-ONLY ACCESS_',
        'prof.library': "'s Library.",
        'prof.courses': 'COURSES',
        'prof.notes': 'NOTES',
        'prof.no_courses': 'NO PUBLIC COURSES FOUND.',
        'prof.no_notes': 'NO NOTES IN THIS COURSE.',
        'prof.save': 'SAVE_',
        'prof.praise': 'PRAISE_',
        'prof.save_note_title': 'Save Note_',
        'prof.no_save_course': "You don't have any courses to save this note to.",
        'prof.select_course': 'Select Course',
        'prof.cancel': 'CANCEL',
        'prof.saving': 'SAVING...',
        'prof.save_to': 'SAVE TO COURSE',
        'login.title': 'Login',
        'login.subtitle': 'Welcome back to the system.',
        'login.error_prefix': 'ERROR:',
        'login.email_label': 'EMAIL_ADDRESS',
        'login.pwd_label': 'PASSWORD',
        'login.authenticating': 'AUTHENTICATING...',
        'login.login_btn': 'LOGIN_',
        'login.no_account': "Don't have an account?",
        'login.register': 'REGISTER',
        'login.fail': 'Login failed. Check your credentials.',
        'reg.fail': 'Registration failed. Check your details.',
        'reg.fail_user': 'Failed to set username.',
        'reg.title_step2': 'PICK_A_HANDLE',
        'reg.subtitle_step2': 'Choose how you will be identified in the JOTROW network.',
        'reg.user_label': 'USERNAME',
        'reg.establishing': 'ESTABLISHING...',
        'reg.finalize': 'FINALIZE_IDENTITIES',
        'reg.modify_later': 'Identity can be modified later in settings.',
        'reg.title_step1': 'JOIN_US',
        'reg.subtitle_step1': 'Initialize new user sequence.',
        'reg.email_label': 'EMAIL_ADDRESS',
        'reg.pwd_label': 'ACCESS_PASSWORD',
        'reg.initializing': 'INITIALIZING...',
        'reg.start': 'START_MISSION_',
        'reg.already': 'Already established?',
        'reg.login': 'LOGIN_HERE',
        'cd.error': 'ERROR:',
        'cd.back': 'BACK_TO_DASHBOARD',
        'cd.dir': 'DIRECTORY:',
        'cd.course_info': 'COURSE_INFO',
        'cd.upload': 'UPLOAD_NEW_JOT',
        'cd.empty': 'Digital archives currently empty.',
        'cd.save': 'SAVE',
        'cd.cancel': 'CANCEL',
        'cd.edit': 'Edit note',
        'cd.delete': 'Delete note',
        'cd.confirm_del': 'Confirm delete?',
        'cd.confirm_btn': 'CONFIRM?',
        'cd.originally_by': 'Originally by',
        'cd.note_placeholder': 'Note content...',
        'nf.title': 'RESOURCE_NOT_FOUND',
        'nf.desc': '[!] ERROR: The page you are looking for has been moved, deleted, or never existed in this timeline.',
        'nf.back': 'BACK_TO_SAFETY_',
        'nf.debug': 'DEBUG_INFO: UNAUTHORIZED_PATH_DETECTED',
    },
    tr: {
        'nav.explore': 'KEŞFET',
        'nav.profile': 'PROFİL',
        'nav.upload': 'YÜKLE_',
        'nav.logout': 'ÇIKIŞ_',
        'nav.login': 'Giriş',
        'nav.register': 'Kayıt Ol',
        'upload.title': 'Not Yükle',
        'profile.settings': 'Ayarlar',
        'home.hero.title_1': 'Düşüncelerini yakala,',
        'home.hero.title_2': 'bilgiye',
        'home.hero.title_3': ' dönüştür.',
        'home.hero.desc': 'Öğrencilerin hızlıca not alması, bunları çalışma materyallerine dönüştürmesi ve 4 haneli güvenli PIN ile paylaşması için minimalist çalışma alanı.',
        'home.hero.launch': 'PANELİ BAŞLAT_',
        'home.hero.start': 'HEMEN BAŞLA_',
        'home.hero.explore': 'NOTLARI KEŞFET_',
        'home.why.rapid': 'Hızlı Kayıt',
        'home.why.rapid_desc': 'Ham düşüncelerini solup gitmeden anında "karala". Dikkat dağıtıcı yok, sadece senin fikirlerin.',
        'home.why.clean': 'Temiz Düzenleme',
        'home.why.clean_desc': 'Dağınık karalamaları Markdown desteğiyle yapılandırılmış, aranabilir çalışma materyallerine dönüştür.',
        'home.why.simple': 'Kolay Paylaşım',
        'home.why.simple_desc': 'Çalışmalarını 4 haneli PIN ile paylaş. Tek tıkla gizli tut veya dünyaya aç.',
        'home.pin.title': 'PIN veya PAPS ile Korumalı',
        'home.pin.desc_1': 'Tüm herkese açık profilini veya belirli notlarını benzersiz 4 haneli Gizli Kodunla veya PAPS karşılığında paylaş.',
        'home.pin.desc_2': 'Başkaları içeriklerine ',
        'home.pin.desc_3': ' adresinde ancak kodunu bilirlerse veya belirlediğin PAPS ücretini öderlerse erişebilir.',
        'home.cta.title': 'Daha akıllı çalışmaya hazır mısın?',
        'home.cta.button': 'BAŞLAT_',
        'dash.total_notes': 'TOPLAM NOT',
        'dash.folders': 'KLASÖRLER',
        'dash.total_praise': 'TOPLAM BEĞENİ',
        'dash.title': 'Benim Yerim',
        'dash.subtitle': 'Hızlı notlar bırakmak ve klasörlerde düzenlemek için merkezi alanınız.',
        'dash.new_folder': 'YENİ KLASÖR',
        'dash.cancel': 'İPTAL',
        'dash.quick_add': 'HIZLI EKLE_',
        'dash.create_folder': 'Yeni Klasör Oluştur',
        'dash.folder_name': 'KLASÖR ADI',
        'dash.desc_optional': 'AÇIKLAMA (İsteğe bağlı)',
        'dash.create': 'OLUŞTUR_',
        'dash.inbox': 'Tek Notlar',
        'dash.not_in_folder': 'hiçbir klasörde değil',
        'dash.move_to': 'Klasöre taşı:',
        'dash.no_folders': 'Henüz klasör yok. Önce bir tane oluşturun.',
        'dash.empty_title': 'Kütüphaneniz boş',
        'dash.empty_desc': 'Hızlıca bir not ekleyin veya notlarınızı düzenlemek için bir klasör oluşturun.',
        'dash.quick_add_note': 'HIZLI NOT EKLE_',
        'dash.create_a_folder': 'KLASÖR OLUŞTUR',
        'dash.no_folders_yet': 'Henüz klasör yok.',
        'dash.create_one': 'Oluşturmak',
        'dash.start_org': 'için notlarınızı düzenlemeye başlayın.',
        'dash.save': 'KAYDET',
        'dash.notes_count': 'NOT',
        'upload.return': 'PANELE DÖN',
        'upload.page_title': 'Not Yükle',
        'upload.select_course': 'KLASÖR SEÇ',
        'upload.no_folder': '-- KÜTÜPHANEYE EKLE (Klasörsüz) --',
        'upload.note_title': 'NOT BAŞLIĞI',
        'upload.title_placeholder': 'Örn. Bölüm 4...',
        'upload.content': 'İÇERİK (Markdown destekli)',
        'upload.content_placeholder': 'Notlarınızı buraya yazın...',
        'upload.attach_images': 'GÖRSEL EKLE',
        'upload.drag_drop': 'BURAYA SÜRÜKLE BIRAK VEYA SEÇMEK İÇİN TIKLA',
        'upload.uploading': 'YÜKLENİYOR...',
        'upload.submit': 'TAMAMLA. YÜKLE_',
        'set.title': 'Ayarlar',
        'set.profile': 'Profil',
        'set.privacy': 'Gizlilik',
        'set.wallet': 'Cüzdan',
        'set.earnings': 'Kazançlar',
        'set.account': 'Hesap',
        'set.public_profile': 'Açık Profil',
        'set.display_name': 'Görünen Ad',
        'set.name_placeholder': 'Tam adınız veya takma adınız',
        'set.bio': 'Hakkında',
        'set.bio_placeholder': 'Kendiniz hakkında kısa bir açıklama...',
        'set.university': 'Üniversite',
        'set.uni_placeholder': 'Örn. İTÜ',
        'set.department': 'Bölüm',
        'set.dept_placeholder': 'Örn. Bilgisayar Mühendisliği',
        'set.save_profile': 'PROFİLİ KAYDET_',
        'set.share_pin': 'Paylaşım PIN (4 Haneli Kod)',
        'set.pin_desc1': 'PIN kodunuz, başkalarının profilinize erişmek için girdiği koddur. Adres:',
        'set.current': 'Mevcut:',
        'set.new_pin': 'Yeni PIN',
        'set.set_pin': 'PIN BELİRLE_',
        'set.privacy_visibility': 'Gizlilik ve Görünürlük',
        'set.default_visibility': 'Varsayılan Not Görünürlüğü',
        'set.private': '🔒 Gizli',
        'set.public': '🌐 Açık',
        'set.private_desc': 'Yeni notlar sadece sizin ve PIN kodunuzu bilen kişilerin erişimine açık olacaktır.',
        'set.public_desc': 'Yeni notlar herkese açık ve keşfedilebilir olacaktır.',
        'set.show_explore': 'Keşfette Göster',
        'set.explore_desc': 'Profilinizin Keşfet / Öne Çıkanlar bölümünde görünmesine izin verin.',
        'set.save_privacy': 'GİZLİLİĞİ KAYDET_',
        'set.paps_balance': 'PAPS Bakiyesi',
        'set.available': 'Kullanılabilir',
        'set.tx_history': 'İşlem Geçmişi',
        'set.no_tx': 'HENÜZ İŞLEM YOK.',
        'set.this_week': "Bu Haftanın Kazançları",
        'set.earned': 'Kazanılan',
        'set.spent': 'Harcanan',
        'set.net': 'Net',
        'set.week_of': 'Hafta:',
        'set.no_activity': 'Bu hafta henüz aktivite yok.',
        'set.change_email': 'E-posta Değiştir',
        'set.new_email': 'Yeni E-posta',
        'set.current_pwd': 'Mevcut Şifre',
        'set.update_email': 'E-POSTAYI GÜNCELLE_',
        'set.change_pwd': 'Şifre Değiştir',
        'set.new_pwd': 'Yeni Şifre',
        'set.confirm_pwd': 'Yeni Şifreyi Onayla',
        'set.update_pwd': 'ŞİFREYİ GÜNCELLE_',
        'set.session': 'Oturum',
        'set.logout': 'ÇIKIŞ YAP_',
        'set.saving': 'KAYDEDİLİYOR...',
        'exp.title': 'Keşfet',
        'exp.subtitle': 'Diğer öğrencilerin notlarını ve klasörlerini keşfedin. Kullanıcı adına göre arayın veya öne çıkan profillere göz atın.',
        'exp.search_label': 'PROFİLLERİ ARA',
        'exp.search_placeholder': 'Kullanıcı adı veya görünen ad...',
        'exp.searching': 'ARANIYOR...',
        'exp.search': 'ARA_',
        'exp.found': 'Bulunan sonuç:',
        'exp.results_for': 'aranan kelime:',
        'exp.clear': 'Aramayı Temizle',
        'exp.search_results': 'Arama Sonuçları',
        'exp.featured': 'Öne Çıkan Profiller',
        'exp.searching_void': 'Boşlukta aranıyor...',
        'exp.no_profiles': 'Eşleşen profil bulunamadı:',
        'exp.try_these': 'Bunun yerine şunları deneyin:',
        'exp.tip1': '• Tam kullanıcı adı veya görünen ad ile arayın',
        'exp.tip2': '• Yazım hatalarını kontrol edin',
        'exp.tip3': '• "demo" profili aramayı deneyin',
        'exp.no_public': 'Henüz açık profil bulunmuyor.',
        'exp.course': 'Klasör',
        'exp.try_demo': 'DEMOYU DENE_',
        'exp.view': 'GÖRÜNTÜLE_',
        'prof.private_title': 'Özel Profil Ayarları',
        'prof.private_desc': 'Ayarlar ve profil yönetimi buradadır.',
        'prof.sys_error': 'Sistem Hatası',
        'prof.not_found': 'Kullanıcı bulunamadı.',
        'prof.encrypted': 'ŞİFRELİ_PROFİL',
        'prof.target': 'Hedef:',
        'prof.enter_pin': '4 HANELİ PIN GİRİN',
        'prof.decrypting': 'ŞİFRE ÇÖZÜLÜYOR...',
        'prof.decrypt': 'ERİŞİM_ŞİFRESİNİ_ÇÖZ',
        'prof.sec_protocol': 'İzinsiz erişim kaydedilir. JOTROW Güvenlik Protokolü v1.4',
        'prof.read_only': 'HERKESE AÇIK SALT OKUNUR ERİŞİM_',
        'prof.library': ' Kütüphanesi.',
        'prof.courses': 'DERSLER',
        'prof.notes': 'NOTLAR',
        'prof.no_courses': 'HERKESE AÇIK DERS BULUNAMADI.',
        'prof.no_notes': 'BU DERSTE NOT BULUNMUYOR.',
        'prof.save': 'KAYDET_',
        'prof.praise': 'ÖVGÜ_',
        'prof.save_note_title': 'Notu Kaydet_',
        'prof.no_save_course': "Bu notu kaydedebileceğiniz bir dersiniz bulunmuyor.",
        'prof.select_course': 'Ders Seç',
        'prof.cancel': 'İPTAL',
        'prof.saving': 'KAYDEDİLİYOR...',
        'prof.save_to': 'DERSE KAYDET',
        'login.title': 'Giriş',
        'login.subtitle': 'Sisteme tekrar hoş geldiniz.',
        'login.error_prefix': 'HATA:',
        'login.email_label': 'E-POSTA_ADRESİ',
        'login.pwd_label': 'ŞİFRE',
        'login.authenticating': 'DOĞRULANIYOR...',
        'login.login_btn': 'GİRİŞ_YAP_',
        'login.no_account': "Hesabınız yok mu?",
        'login.register': 'KAYIT OL',
        'login.fail': 'Giriş yapılamadı. Bilgilerinizi kontrol edin.',
        'reg.fail': 'Kayıt başarısız. Bilgilerinizi kontrol edin.',
        'reg.fail_user': 'Kullanıcı adı ayarlanamadı.',
        'reg.title_step2': 'KULLANICI_ADI_SEÇ',
        'reg.subtitle_step2': 'JOTROW ağında nasıl tanımlanacağınızı seçin.',
        'reg.user_label': 'KULLANICI_ADI',
        'reg.establishing': 'BAĞLANTI_KURULUYOR...',
        'reg.finalize': 'KİMLİĞİ_TAMAMLA',
        'reg.modify_later': 'Kimlik daha sonra ayarlardan değiştirilebilir.',
        'reg.title_step1': 'BİZE_KATIL',
        'reg.subtitle_step1': 'Yeni kullanıcı dizisini başlat.',
        'reg.email_label': 'E-POSTA_ADRESİ',
        'reg.pwd_label': 'ERİŞİM_ŞİFRESİ',
        'reg.initializing': 'BAŞLATILIYOR...',
        'reg.start': 'GÖREVİ_BAŞLAT_',
        'reg.already': 'Zaten kayıtlı mısın?',
        'reg.login': 'BURADAN_GİRİŞ_YAP',
        'cd.error': 'HATA:',
        'cd.back': 'PANELİ_GERİ_DÖN',
        'cd.dir': 'DİZİN:',
        'cd.course_info': 'DERS_BİLGİSİ',
        'cd.upload': 'YENİ_NOT_EKLE',
        'cd.empty': 'Dijital arşivler şu an boş.',
        'cd.save': 'KAYDET',
        'cd.cancel': 'İPTAL',
        'cd.edit': 'Notu düzenle',
        'cd.delete': 'Notu sil',
        'cd.confirm_del': 'Silmeyi onayla?',
        'cd.confirm_btn': 'ONAYLA?',
        'cd.originally_by': 'Orijinal yazar',
        'cd.note_placeholder': 'Not içeriği...',
        'nf.title': 'KAYNAK_BULUNAMADI',
        'nf.desc': '[!] HATA: Aradığınız sayfa taşınmış, silinmiş veya bu zaman çizelgesinde hiç var olmamış olabilir.',
        'nf.back': 'GÜVENLİ_BÖLGEYE_DÖN_',
        'nf.debug': 'HATA_AYIKLAMA_BİLGİSİ: YETKİSİZ_YOL_TESPİT_EDİLDİ',
    }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>(() => {
        const saved = localStorage.getItem('jotrow_lang');
        if (saved === 'en' || saved === 'tr') return saved;
        // Default to browser language or 'en'
        const browserLang = navigator.language.split('-')[0];
        return browserLang === 'tr' ? 'tr' : 'en';
    });

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('jotrow_lang', lang);
    };

    const t = (key: string): string => {
        return translations[language]?.[key] || translations['en'][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
