"""Make note course_id nullable

Revision ID: 1f45c1d5bd9f
Revises: 085bc0fb2f4c
Create Date: 2026-03-07 19:44:39.981439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f45c1d5bd9f'
down_revision: Union[str, Sequence[str], None] = '085bc0fb2f4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
