"""add original_author to notes

Revision ID: 291f565552bd
Revises: 40a6f13fe461
Create Date: 2026-03-07 02:43:18.331399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '291f565552bd'
down_revision: Union[str, Sequence[str], None] = '40a6f13fe461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('original_author', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'original_author')
    # ### end Alembic commands ###
