"""add praise_count to notes

Revision ID: 40a6f13fe461
Revises: a7536a5c35a3
Create Date: 2026-03-07 02:20:27.687803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40a6f13fe461'
down_revision: Union[str, Sequence[str], None] = 'a7536a5c35a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('praise_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'praise_count')
    # ### end Alembic commands ###
