"""add owner_id to Note

Revision ID: 966d0ac93abf
Revises: 5a9e1c2d3f4b
Create Date: 2026-03-08 17:36:06.516750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '966d0ac93abf'
down_revision: Union[str, Sequence[str], None] = '5a9e1c2d3f4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'owner_id')
    # ### end Alembic commands ###
